# Generated by Django 4.0 on 2021-12-19 13:31
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id_catalog', models.AutoField(primary_key=True, serialize=False, verbose_name='id_catalog')),
                ('namecat', models.CharField(max_length=20, verbose_name='Каталог')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False, verbose_name='id_file')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('extension', models.CharField(max_length=20, verbose_name='Расширение')),
                ('id_catalog', models.ForeignKey(db_column='id_catalog', on_delete=django.db.models.deletion.DO_NOTHING, to='PK2.catalog')),
            ],
        ),
    ]
