# Generated by Django 4.0 on 2021-12-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PK2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='namecat',
            new_name='name',
        ),
    ]
