# Generated by Django 4.0 on 2021-12-13 10:03
from django.db import migrations, models
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя художника')),
                ('country', models.CharField(max_length=40, verbose_name='Страна')),
                ('arts', models.CharField(max_length=100, verbose_name='Известные работы')),
                ('is_impressionism', models.BooleanField(verbose_name='Художник работал в жанре импрессионизм?')),
            ],
        ),
    ]
